language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-20.0.0
    - android-15
    - sys-img-armeabi-v7a-android-tv-15
    - add-on
    - extra
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 89528662f405e6e1fee62471dac7e6238b59c26a # Set in travis-ci.org dashboard
  on:
    branch: test
